### PR TITLE
Feature/tri 294 configuration of ci cd pipeline in new repository

### PR DESCRIPTION
**Pull request by ds-ext-ooyeneye**

### CODE REVIEW

**Review by ds-ext-kmassalski — APPROVED** [review]
Approved, but I am not sure if we want to move to JDK17.
Please reopen and merge this one if needed:
https://github.com/catenax/ItemRelationshipServices/pull/3

**Comment by ds-ext-kmassalski** [comment]
@ds-ext-ooyeneye branch has conflicts. Please resolve. Addiotonaly pls check my comment above.

**Comment by ds-ext-kmassalski** [comment]
@ds-ext-ooyeneye branch has conflicts. Please resolve. Addiotonaly pls check my comment above.

**Review by ds-ext-kmassalski — CHANGES_REQUESTED** [review]
Conflicts with main branch

**Comment by ds-jkreutzfeld** [comment]
I don't think this is relevant any longer.

**Pull request closed without merging**
